#!/bin/bash

. arin-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing arin-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") TODO

Download the contents of a storage device to an image file.
DOCSTRING
}

checkForHelp $1


